### ISSUE TITLE
Remove dart:mirror usage from package:http

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/http#1]
A change to the dart2js compiler introduced a warning on mirror usage in dart code -- see [Emit warning on import of dart:mirrors.](https://codereview.chromium.org//588183002). According to the warning, users will be forced to pass an additional flag to the dart2js compiler when their code is using dart:mirrors. This affects all users of `package:http`.

When compiling the following example

``` dart
import 'package:http/http.dart';
main()=> print("hello");
```

dart2js will print out the following warning:

```
Warning: 
****************************************************************
* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.
*
* Your app imports dart:mirrors via:
*   x.dart => package:http => dart:mirrors
*
* Starting with Dart 1.9, you must use the
* --enable-experimental-mirrors command-line flag to opt-in.
* You can begin using this flag now if mirrors support is critical.
*
* To learn what to do next, please visit:
*    http://dartlang.org/dart2js-reflection
****************************************************************
```

That flag does not seem to be enforced as of SDK version 1.9.0-dev.1.0+google3-trunk, but that seems to be only a matter of time.

**Comment by nex3** [comment]
This is blocked on having a viable alternative ([issue 6943](https://code.google.com/p/dart/issues/detail?id=6943)). I believe the end result of the discussion about this warning was that it also shouldn't be introduced until a viable alternative to mirrors exists.

**Comment by skybrian** [comment]
I'm told this warning is spurious and dart2js should be fixed to only print it when code size is actually affected.

**Comment by skybrian** [comment]
Here's the bug for fixing dart2js:
https://code.google.com/p/dart/issues/detail?id=23293

**Comment by anders-sandholm** [comment]
Just wondering, how can we get package http to not use mirrors, such that it can be used "out of the box" by Flutter? 

See also this discussion https://github.com/flutter/flutter/issues/5831#issuecomment-246517611 

Given that cross-platform package support is not there, what is the best viable way to solve this in the short term?

**Comment by anders-sandholm** [comment]
Having talked to @floitschG it seems we might be able to rewrite things in a way that uses config-specific imports instead of mirrors. 

Config-specific imports are tracked here https://github.com/dart-lang/sdk/issues/24581. 
DDC is currently still missing (https://github.com/dart-lang/dev_compiler/issues/595).

**Comment by matanlurey** [comment]
Nice!

**Comment by nex3** [comment]
I'm definitely planning on rewriting this with config-specific imports—I
even have a local branch that suits it. But the the feature needs to no
longer be behind a flag, and to be sorted by DDC, for that branch to be
releasable.

**Comment by chinmaygarde** [comment]
Flutter would be extremely excited to finally use the package directly. If you are willing to publish the local branch separately, we can even test it out for you by specifying the package as a Git dependency.

Thanks.

**Comment by sethladd** [comment]
Thanks @nex3 ! We'd love to DEP in your branch so we can use http again.

**Comment by eseidelGoogle** [comment]
Flutter has checked in a forked copy of http/http.dart for the time being:
https://github.com/flutter/flutter/commit/400585cb96064db50f9574361b6a471f3dbf4787

We'll happily remove it as soon as this is resolved.  Thanks!

**Comment by nex3** [comment]
I've pushed my local changes in [the cross-platform branch](https://github.com/dart-lang/http/tree/cross-platform). Heads up: it's not especially thoroughly tested.

**Comment by sethladd** [comment]
Thanks!

**Comment by eseidelGoogle** [comment]
Curious for an update?  Folks are attempting to use package:http-dependent packages in Flutter and are I believe blocked by this bug.

Theoretically users could use dependency_override to override package:http to point to packages/flutter/lib/src/http, but I've not actually seen that work yet.
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

**Comment by sethladd** [comment]
An internal dev got dependency overrides working, but we needed to create a fake http package which imports Flutter's http package and reexports everything. Then, we put that fake http package onto git, so it could be pulled down during pub's download/resolution step.

**Comment by nex3** [comment]
This is still blocked on getting interface libraries implemented everywhere and out from behind the flag.

**Comment by eseidelGoogle** [comment]
@nex3 could you remind me which issues(s) those are?  Presumably some subset of the ones mentioned in earlier comments?

**Comment by nex3** [comment]
dart-lang/sdk#24581 is the tracking issue for config-specific imports.

**Comment by mit-mit** [comment]
@nex3 removing blocked field, as per https://github.com/dart-lang/sdk/issues/24581#issuecomment-267616478 all main pieces have landed and verified in a new test case.

Can we try out this package change now?

**Comment by nex3** [comment]
@mit-mit There's not much we can do until the feature is available in a stable release.

**Comment by mit-mit** [comment]
Oh, good point. That is scheduled for late January!

**Comment by eseidelGoogle** [comment]
The approach on how to do this was re-thought.  My understanding is that this blocking work will be done by April for sure, and likely much sooner.
